# TO BE LATER AUTOGENERATED

import
  std / tables,
  std / unicode

type
  CollationElement* = object
    level1*: uint16
    level2*: uint16  # 0000 if none
    level3*: uint16  # 0000 if none
    shifted*: bool

const
  rawCollations* = {
    Rune(0x006B  ): @[                                     # LATIN SMALL LETTER K
      CollationElement(level1: uint16(0x219C), level2: uint16(0x0020), level3: uint16(0x0002), shifted: false)
    ],
    Rune(0xFF4B  ): @[                                     # FULLWIDTH LATIN SMALL LETTER K
      CollationElement(level1: uint16(0x219C), level2: uint16(0x0020), level3: uint16(0x0003), shifted: false)
    ],
    Rune(0x1DDC  ): @[                                     # COMBINING LATIN SMALL LETTER K
      CollationElement(level1: uint16(0x219C), level2: uint16(0x0020), level3: uint16(0x0004), shifted: false)
    ],
    Rune(0x24A6  ): @[                                     # PARENTHESIZED LATIN SMALL LETTER K
      CollationElement(level1: uint16(0x0334), level2: uint16(0x0020), level3: uint16(0x0004), shifted: true ),
      CollationElement(level1: uint16(0x219C), level2: uint16(0x0020), level3: uint16(0x0004), shifted: false),
      CollationElement(level1: uint16(0x0335), level2: uint16(0x0020), level3: uint16(0x0004), shifted: true )
    ],
    Rune(0x1D424 ): @[                                     # MATHEMATICAL BOLD SMALL K
      CollationElement(level1: uint16(0x219C), level2: uint16(0x0020), level3: uint16(0x0005), shifted: false)
    ],
    Rune(0x1D458 ): @[                                     # MATHEMATICAL ITALIC SMALL K
      CollationElement(level1: uint16(0x219C), level2: uint16(0x0020), level3: uint16(0x0005), shifted: false)
    ],
    Rune(0x1D48C ): @[                                     # MATHEMATICAL BOLD ITALIC SMALL K
      CollationElement(level1: uint16(0x219C), level2: uint16(0x0020), level3: uint16(0x0005), shifted: false)
    ],
    Rune(0x1D4C0 ): @[                                     # MATHEMATICAL SCRIPT SMALL K
      CollationElement(level1: uint16(0x219C), level2: uint16(0x0020), level3: uint16(0x0005), shifted: false)
    ],
    Rune(0x1D4F4 ): @[                                     # MATHEMATICAL BOLD SCRIPT SMALL K
      CollationElement(level1: uint16(0x219C), level2: uint16(0x0020), level3: uint16(0x0005), shifted: false)
    ],
    Rune(0x1D528 ): @[                                     # MATHEMATICAL FRAKTUR SMALL K
      CollationElement(level1: uint16(0x219C), level2: uint16(0x0020), level3: uint16(0x0005), shifted: false)
    ],
    Rune(0x1D55C ): @[                                     # MATHEMATICAL DOUBLE-STRUCK SMALL K
      CollationElement(level1: uint16(0x219C), level2: uint16(0x0020), level3: uint16(0x0005), shifted: false)
    ],
    Rune(0x1D590 ): @[                                     # MATHEMATICAL BOLD FRAKTUR SMALL K
      CollationElement(level1: uint16(0x219C), level2: uint16(0x0020), level3: uint16(0x0005), shifted: false)
    ],
    Rune(0x1D5C4 ): @[                                     # MATHEMATICAL SANS-SERIF SMALL K
      CollationElement(level1: uint16(0x219C), level2: uint16(0x0020), level3: uint16(0x0005), shifted: false)
    ],
    Rune(0x1D5F8 ): @[                                     # MATHEMATICAL SANS-SERIF BOLD SMALL K
      CollationElement(level1: uint16(0x219C), level2: uint16(0x0020), level3: uint16(0x0005), shifted: false)
    ],
    Rune(0x1D62C ): @[                                     # MATHEMATICAL SANS-SERIF ITALIC SMALL K
      CollationElement(level1: uint16(0x219C), level2: uint16(0x0020), level3: uint16(0x0005), shifted: false)
    ],
    Rune(0x1D660 ): @[                                     # MATHEMATICAL SANS-SERIF BOLD ITALIC SMALL K
      CollationElement(level1: uint16(0x219C), level2: uint16(0x0020), level3: uint16(0x0005), shifted: false)
    ],
    Rune(0x1D694 ): @[                                     # MATHEMATICAL MONOSPACE SMALL K
      CollationElement(level1: uint16(0x219C), level2: uint16(0x0020), level3: uint16(0x0005), shifted: false)
    ],
    Rune(0x24DA  ): @[                                     # CIRCLED LATIN SMALL LETTER K
      CollationElement(level1: uint16(0x219C), level2: uint16(0x0020), level3: uint16(0x0006), shifted: false)
    ],
    Rune(0x004B  ): @[                                     # LATIN CAPITAL LETTER K
      CollationElement(level1: uint16(0x219C), level2: uint16(0x0020), level3: uint16(0x0008), shifted: false)
    ],
    Rune(0x212A  ): @[                                     # KELVIN SIGN
      CollationElement(level1: uint16(0x219C), level2: uint16(0x0020), level3: uint16(0x0008), shifted: false)
    ],
    Rune(0xFF2B  ): @[                                     # FULLWIDTH LATIN CAPITAL LETTER K
      CollationElement(level1: uint16(0x219C), level2: uint16(0x0020), level3: uint16(0x0009), shifted: false)
    ],
    Rune(0x1F11A ): @[                                     # PARENTHESIZED LATIN CAPITAL LETTER K
      CollationElement(level1: uint16(0x0334), level2: uint16(0x0020), level3: uint16(0x0004), shifted: true ),
      CollationElement(level1: uint16(0x219C), level2: uint16(0x0020), level3: uint16(0x000A), shifted: false),
      CollationElement(level1: uint16(0x0335), level2: uint16(0x0020), level3: uint16(0x0004), shifted: true )
    ],
    Rune(0x1D40A ): @[                                     # MATHEMATICAL BOLD CAPITAL K
      CollationElement(level1: uint16(0x219C), level2: uint16(0x0020), level3: uint16(0x000B), shifted: false)
    ],
    Rune(0x1D43E ): @[                                     # MATHEMATICAL ITALIC CAPITAL K
      CollationElement(level1: uint16(0x219C), level2: uint16(0x0020), level3: uint16(0x000B), shifted: false)
    ],
    Rune(0x1D472 ): @[                                     # MATHEMATICAL BOLD ITALIC CAPITAL K
      CollationElement(level1: uint16(0x219C), level2: uint16(0x0020), level3: uint16(0x000B), shifted: false)
    ],
    Rune(0x1D4A6 ): @[                                     # MATHEMATICAL SCRIPT CAPITAL K
      CollationElement(level1: uint16(0x219C), level2: uint16(0x0020), level3: uint16(0x000B), shifted: false)
    ],
    Rune(0x1D4DA ): @[                                     # MATHEMATICAL BOLD SCRIPT CAPITAL K
      CollationElement(level1: uint16(0x219C), level2: uint16(0x0020), level3: uint16(0x000B), shifted: false)
    ],
    Rune(0x1D50E ): @[                                     # MATHEMATICAL FRAKTUR CAPITAL K
      CollationElement(level1: uint16(0x219C), level2: uint16(0x0020), level3: uint16(0x000B), shifted: false)
    ],
    Rune(0x1D542 ): @[                                     # MATHEMATICAL DOUBLE-STRUCK CAPITAL K
      CollationElement(level1: uint16(0x219C), level2: uint16(0x0020), level3: uint16(0x000B), shifted: false)
    ],
    Rune(0x1D576 ): @[                                     # MATHEMATICAL BOLD FRAKTUR CAPITAL K
      CollationElement(level1: uint16(0x219C), level2: uint16(0x0020), level3: uint16(0x000B), shifted: false)
    ],
    Rune(0x1D5AA ): @[                                     # MATHEMATICAL SANS-SERIF CAPITAL K
      CollationElement(level1: uint16(0x219C), level2: uint16(0x0020), level3: uint16(0x000B), shifted: false)
    ],
    Rune(0x1D5DE ): @[                                     # MATHEMATICAL SANS-SERIF BOLD CAPITAL K
      CollationElement(level1: uint16(0x219C), level2: uint16(0x0020), level3: uint16(0x000B), shifted: false)
    ],
    Rune(0x1D612 ): @[                                     # MATHEMATICAL SANS-SERIF ITALIC CAPITAL K
      CollationElement(level1: uint16(0x219C), level2: uint16(0x0020), level3: uint16(0x000B), shifted: false)
    ],
    Rune(0x1D646 ): @[                                     # MATHEMATICAL SANS-SERIF BOLD ITALIC CAPITAL K
      CollationElement(level1: uint16(0x219C), level2: uint16(0x0020), level3: uint16(0x000B), shifted: false)
    ],
    Rune(0x1D67A ): @[                                     # MATHEMATICAL MONOSPACE CAPITAL K
      CollationElement(level1: uint16(0x219C), level2: uint16(0x0020), level3: uint16(0x000B), shifted: false)
    ],
    Rune(0x24C0  ): @[                                     # CIRCLED LATIN CAPITAL LETTER K
      CollationElement(level1: uint16(0x219C), level2: uint16(0x0020), level3: uint16(0x000C), shifted: false)
    ],
    Rune(0x1F15A ): @[                                     # NEGATIVE CIRCLED LATIN CAPITAL LETTER K
      CollationElement(level1: uint16(0x219C), level2: uint16(0x0020), level3: uint16(0x000C), shifted: false)
    ],
    Rune(0x1D4F  ): @[                                     # MODIFIER LETTER SMALL K
      CollationElement(level1: uint16(0x219C), level2: uint16(0x0020), level3: uint16(0x0014), shifted: false)
    ],
    Rune(0x2096  ): @[                                     # LATIN SUBSCRIPT SMALL LETTER K
      CollationElement(level1: uint16(0x219C), level2: uint16(0x0020), level3: uint16(0x0015), shifted: false)
    ],
    Rune(0x1D37  ): @[                                     # MODIFIER LETTER CAPITAL K
      CollationElement(level1: uint16(0x219C), level2: uint16(0x0020), level3: uint16(0x001D), shifted: false)
    ],
    Rune(0x1F13A ): @[                                     # SQUARED LATIN CAPITAL LETTER K
      CollationElement(level1: uint16(0x219C), level2: uint16(0x0020), level3: uint16(0x001D), shifted: false)
    ],
    Rune(0x1F17A ): @[                                     # NEGATIVE SQUARED LATIN CAPITAL LETTER K
      CollationElement(level1: uint16(0x219C), level2: uint16(0x0020), level3: uint16(0x001D), shifted: false)
    ],
    Rune(0x1E31  ): @[                                     # LATIN SMALL LETTER K WITH ACUTE
      CollationElement(level1: uint16(0x219C), level2: uint16(0x0020), level3: uint16(0x0002), shifted: false),
      CollationElement(level1: uint16(0x0000), level2: uint16(0x0024), level3: uint16(0x0002), shifted: false)
    ],
    Rune(0x1E30  ): @[                                     # LATIN CAPITAL LETTER K WITH ACUTE
      CollationElement(level1: uint16(0x219C), level2: uint16(0x0020), level3: uint16(0x0008), shifted: false),
      CollationElement(level1: uint16(0x0000), level2: uint16(0x0024), level3: uint16(0x0002), shifted: false)
    ],
    Rune(0x01E9  ): @[                                     # LATIN SMALL LETTER K WITH CARON
      CollationElement(level1: uint16(0x219C), level2: uint16(0x0020), level3: uint16(0x0002), shifted: false),
      CollationElement(level1: uint16(0x0000), level2: uint16(0x0028), level3: uint16(0x0002), shifted: false)
    ],
    Rune(0x01E8  ): @[                                     # LATIN CAPITAL LETTER K WITH CARON
      CollationElement(level1: uint16(0x219C), level2: uint16(0x0020), level3: uint16(0x0008), shifted: false),
      CollationElement(level1: uint16(0x0000), level2: uint16(0x0028), level3: uint16(0x0002), shifted: false)
    ],
    Rune(0x0137  ): @[                                     # LATIN SMALL LETTER K WITH CEDILLA
      CollationElement(level1: uint16(0x219C), level2: uint16(0x0020), level3: uint16(0x0002), shifted: false),
      CollationElement(level1: uint16(0x0000), level2: uint16(0x0030), level3: uint16(0x0002), shifted: false)
    ],
    Rune(0x0136  ): @[                                     # LATIN CAPITAL LETTER K WITH CEDILLA
      CollationElement(level1: uint16(0x219C), level2: uint16(0x0020), level3: uint16(0x0008), shifted: false),
      CollationElement(level1: uint16(0x0000), level2: uint16(0x0030), level3: uint16(0x0002), shifted: false)
    ],
    Rune(0xA7A3  ): @[                                     # LATIN SMALL LETTER K WITH OBLIQUE STROKE
      CollationElement(level1: uint16(0x219C), level2: uint16(0x0020), level3: uint16(0x0004), shifted: false),
      CollationElement(level1: uint16(0x0000), level2: uint16(0x0035), level3: uint16(0x0004), shifted: false)
    ],
    Rune(0xA7A2  ): @[                                     # LATIN CAPITAL LETTER K WITH OBLIQUE STROKE
      CollationElement(level1: uint16(0x219C), level2: uint16(0x0020), level3: uint16(0x000A), shifted: false),
      CollationElement(level1: uint16(0x0000), level2: uint16(0x0035), level3: uint16(0x0004), shifted: false)
    ],
    Rune(0x1E33  ): @[                                     # LATIN SMALL LETTER K WITH DOT BELOW
      CollationElement(level1: uint16(0x219C), level2: uint16(0x0020), level3: uint16(0x0002), shifted: false),
      CollationElement(level1: uint16(0x0000), level2: uint16(0x0042), level3: uint16(0x0002), shifted: false)
    ],
    Rune(0x1E32  ): @[                                     # LATIN CAPITAL LETTER K WITH DOT BELOW
      CollationElement(level1: uint16(0x219C), level2: uint16(0x0020), level3: uint16(0x0008), shifted: false),
      CollationElement(level1: uint16(0x0000), level2: uint16(0x0042), level3: uint16(0x0002), shifted: false)
    ],
    Rune(0x1E35  ): @[                                     # LATIN SMALL LETTER K WITH LINE BELOW
      CollationElement(level1: uint16(0x219C), level2: uint16(0x0020), level3: uint16(0x0002), shifted: false),
      CollationElement(level1: uint16(0x0000), level2: uint16(0x0049), level3: uint16(0x0002), shifted: false)
    ],
    Rune(0x1E34  ): @[                                     # LATIN CAPITAL LETTER K WITH LINE BELOW
      CollationElement(level1: uint16(0x219C), level2: uint16(0x0020), level3: uint16(0x0008), shifted: false),
      CollationElement(level1: uint16(0x0000), level2: uint16(0x0049), level3: uint16(0x0002), shifted: false)
    ],
    Rune(0x3384  ): @[                                     # SQUARE KA
      CollationElement(level1: uint16(0x219C), level2: uint16(0x0020), level3: uint16(0x001C), shifted: false),
      CollationElement(level1: uint16(0x2075), level2: uint16(0x0020), level3: uint16(0x001D), shifted: false)
    ],
    Rune(0x3385  ): @[                                     # SQUARE KB
      CollationElement(level1: uint16(0x219C), level2: uint16(0x0020), level3: uint16(0x001D), shifted: false),
      CollationElement(level1: uint16(0x208F), level2: uint16(0x0020), level3: uint16(0x001D), shifted: false)
    ],
    Rune(0x3389  ): @[                                     # SQUARE KCAL
      CollationElement(level1: uint16(0x219C), level2: uint16(0x0020), level3: uint16(0x001C), shifted: false),
      CollationElement(level1: uint16(0x20A9), level2: uint16(0x0020), level3: uint16(0x001C), shifted: false),
      CollationElement(level1: uint16(0x2075), level2: uint16(0x0020), level3: uint16(0x001C), shifted: false),
      CollationElement(level1: uint16(0x21B0), level2: uint16(0x0020), level3: uint16(0x001C), shifted: false)
    ],
    Rune(0x338F  ): @[                                     # SQUARE KG
      CollationElement(level1: uint16(0x219C), level2: uint16(0x0020), level3: uint16(0x001C), shifted: false),
      CollationElement(level1: uint16(0x2125), level2: uint16(0x0020), level3: uint16(0x001C), shifted: false)
    ],
    Rune(0x3391  ): @[                                     # SQUARE KHZ
      CollationElement(level1: uint16(0x219C), level2: uint16(0x0020), level3: uint16(0x001C), shifted: false),
      CollationElement(level1: uint16(0x214C), level2: uint16(0x0020), level3: uint16(0x001D), shifted: false),
      CollationElement(level1: uint16(0x236F), level2: uint16(0x0020), level3: uint16(0x001C), shifted: false)
    ],
    Rune(0x33CD  ): @[                                     # SQUARE KK
      CollationElement(level1: uint16(0x219C), level2: uint16(0x0020), level3: uint16(0x001D), shifted: false),
      CollationElement(level1: uint16(0x219C), level2: uint16(0x0020), level3: uint16(0x001D), shifted: false)
    ],
    Rune(0x3398  ): @[                                     # SQUARE KL
      CollationElement(level1: uint16(0x219C), level2: uint16(0x0020), level3: uint16(0x001C), shifted: false),
      CollationElement(level1: uint16(0x21B0), level2: uint16(0x0020), level3: uint16(0x001C), shifted: false)
    ],
    Rune(0x339E  ): @[                                     # SQUARE KM
      CollationElement(level1: uint16(0x219C), level2: uint16(0x0020), level3: uint16(0x001C), shifted: false),
      CollationElement(level1: uint16(0x21E8), level2: uint16(0x0020), level3: uint16(0x001C), shifted: false)
    ],
    Rune(0x33CE  ): @[                                     # SQUARE KM CAPITAL
      CollationElement(level1: uint16(0x219C), level2: uint16(0x0020), level3: uint16(0x001D), shifted: false),
      CollationElement(level1: uint16(0x21E8), level2: uint16(0x0020), level3: uint16(0x001D), shifted: false)
    ],
    Rune(0x33A2  ): @[                                     # SQUARE KM SQUARED
      CollationElement(level1: uint16(0x219C), level2: uint16(0x0020), level3: uint16(0x001C), shifted: false),
      CollationElement(level1: uint16(0x21E8), level2: uint16(0x0020), level3: uint16(0x001C), shifted: false),
      CollationElement(level1: uint16(0x206D), level2: uint16(0x0020), level3: uint16(0x001C), shifted: false)
    ],
    Rune(0x33A6  ): @[                                     # SQUARE KM CUBED
      CollationElement(level1: uint16(0x219C), level2: uint16(0x0020), level3: uint16(0x001C), shifted: false),
      CollationElement(level1: uint16(0x21E8), level2: uint16(0x0020), level3: uint16(0x001C), shifted: false),
      CollationElement(level1: uint16(0x206E), level2: uint16(0x0020), level3: uint16(0x001C), shifted: false)
    ],
    Rune(0x33AA  ): @[                                     # SQUARE KPA
      CollationElement(level1: uint16(0x219C), level2: uint16(0x0020), level3: uint16(0x001C), shifted: false),
      CollationElement(level1: uint16(0x224D), level2: uint16(0x0020), level3: uint16(0x001D), shifted: false),
      CollationElement(level1: uint16(0x2075), level2: uint16(0x0020), level3: uint16(0x001C), shifted: false)
    ],
    Rune(0x33CF  ): @[                                     # SQUARE KT
      CollationElement(level1: uint16(0x219C), level2: uint16(0x0020), level3: uint16(0x001C), shifted: false),
      CollationElement(level1: uint16(0x22DF), level2: uint16(0x0020), level3: uint16(0x001C), shifted: false)
    ],
    Rune(0x33B8  ): @[                                     # SQUARE KV
      CollationElement(level1: uint16(0x219C), level2: uint16(0x0020), level3: uint16(0x001C), shifted: false),
      CollationElement(level1: uint16(0x2331), level2: uint16(0x0020), level3: uint16(0x001D), shifted: false)
    ],
    Rune(0x33BE  ): @[                                     # SQUARE KW
      CollationElement(level1: uint16(0x219C), level2: uint16(0x0020), level3: uint16(0x001C), shifted: false),
      CollationElement(level1: uint16(0x2343), level2: uint16(0x0020), level3: uint16(0x001D), shifted: false)
    ],
    Rune(0x33C0  ): @[                                     # SQUARE K OHM
      CollationElement(level1: uint16(0x219C), level2: uint16(0x0020), level3: uint16(0x001C), shifted: false),
      CollationElement(level1: uint16(0x2435), level2: uint16(0x0020), level3: uint16(0x001D), shifted: false)
    ],
    Rune(0x1D0B  ): @[                                     # LATIN LETTER SMALL CAPITAL K
      CollationElement(level1: uint16(0x21A0), level2: uint16(0x0020), level3: uint16(0x0002), shifted: false)
    ],
    Rune(0x1D84  ): @[                                     # LATIN SMALL LETTER K WITH PALATAL HOOK
      CollationElement(level1: uint16(0x21A1), level2: uint16(0x0020), level3: uint16(0x0002), shifted: false)
    ],
    Rune(0x0199  ): @[                                     # LATIN SMALL LETTER K WITH HOOK
      CollationElement(level1: uint16(0x21A2), level2: uint16(0x0020), level3: uint16(0x0002), shifted: false)
    ],
    Rune(0x0198  ): @[                                     # LATIN CAPITAL LETTER K WITH HOOK
      CollationElement(level1: uint16(0x21A2), level2: uint16(0x0020), level3: uint16(0x0008), shifted: false)
    ],
    Rune(0x2C6A  ): @[                                     # LATIN SMALL LETTER K WITH DESCENDER
      CollationElement(level1: uint16(0x21A6), level2: uint16(0x0020), level3: uint16(0x0002), shifted: false)
    ],
    Rune(0x2C69  ): @[                                     # LATIN CAPITAL LETTER K WITH DESCENDER
      CollationElement(level1: uint16(0x21A6), level2: uint16(0x0020), level3: uint16(0x0008), shifted: false)
    ],
    Rune(0xA741  ): @[                                     # LATIN SMALL LETTER K WITH STROKE
      CollationElement(level1: uint16(0x21A7), level2: uint16(0x0020), level3: uint16(0x0002), shifted: false)
    ],
    Rune(0xA740  ): @[                                     # LATIN CAPITAL LETTER K WITH STROKE
      CollationElement(level1: uint16(0x21A7), level2: uint16(0x0020), level3: uint16(0x0008), shifted: false)
    ],
    Rune(0xA743  ): @[                                     # LATIN SMALL LETTER K WITH DIAGONAL STROKE
      CollationElement(level1: uint16(0x21A8), level2: uint16(0x0020), level3: uint16(0x0002), shifted: false)
    ],
    Rune(0xA742  ): @[                                     # LATIN CAPITAL LETTER K WITH DIAGONAL STROKE
      CollationElement(level1: uint16(0x21A8), level2: uint16(0x0020), level3: uint16(0x0008), shifted: false)
    ],
    Rune(0xA745  ): @[                                     # LATIN SMALL LETTER K WITH STROKE AND DIAGONAL STROKE
      CollationElement(level1: uint16(0x21A9), level2: uint16(0x0020), level3: uint16(0x0002), shifted: false)
    ],
    Rune(0xA744  ): @[                                     # LATIN CAPITAL LETTER K WITH STROKE AND DIAGONAL STROKE
      CollationElement(level1: uint16(0x21A9), level2: uint16(0x0020), level3: uint16(0x0008), shifted: false)
    ],
    Rune(0x1DF03 ): @[                                     # LATIN SMALL LETTER REVERSED K
      CollationElement(level1: uint16(0x21AA), level2: uint16(0x0020), level3: uint16(0x0002), shifted: false)
    ],
    Rune(0x029E  ): @[                                     # LATIN SMALL LETTER TURNED K
      CollationElement(level1: uint16(0x21AB), level2: uint16(0x0020), level3: uint16(0x0002), shifted: false)
    ],
    Rune(0xA7B0  ): @[                                     # LATIN CAPITAL LETTER TURNED K
      CollationElement(level1: uint16(0x21AB), level2: uint16(0x0020), level3: uint16(0x0008), shifted: false)
    ],
    Rune(0x1DF10 ): @[                                     # LATIN LETTER SMALL CAPITAL TURNED K
      CollationElement(level1: uint16(0x21AF), level2: uint16(0x0020), level3: uint16(0x0002), shifted: false)
    ]
  }.toTable
